const { DataTypes } = require('sequelize');
const { sequelize } = require('../database');

const QuestionType = {
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  LIKERT_SCALE: 'LIKERT_SCALE'
};

const Question = sequelize.define('Question', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  question_text: {
    type: DataTypes.TEXT,
    allowNull: false
  },
  question_type: {
    type: DataTypes.ENUM('MULTIPLE_CHOICE', 'LIKERT_SCALE'),
    allowNull: false
  },
  options: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  correct_answer: {
    type: DataTypes.STRING(10),
    allowNull: true
  },
  scale_value: {
    type: DataTypes.INTEGER,
    allowNull: true,
    comment: 'For LIKERT_SCALE questions'
  },
  category: {
    type: DataTypes.STRING(100),
    allowNull: true
  },
  difficulty_level: {
    type: DataTypes.ENUM('Easy', 'Medium', 'Hard'),
    allowNull: true,
    defaultValue: 'Medium'
  },
  status: {
    type: DataTypes.ENUM('pending', 'approved', 'rejected', 'inactive'),
    allowNull: false,
    defaultValue: 'pending',
    comment: 'pending: awaiting approval, approved: can be used in tests, rejected: cannot be used, inactive: deactivated'
  },
  source: {
    type: DataTypes.ENUM('ADMIN', 'AI'),
    allowNull: false,
    defaultValue: 'ADMIN',
    comment: 'ADMIN: created by admin, AI: generated by AI'
  },
  created_by: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'users',
      key: 'id'
    },
    comment: 'Admin user who created this question'
  },
  section_id: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'sections',
      key: 'id'
    },
    onDelete: 'SET NULL'
  },
  is_active: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: true
  },
  order_index: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 0
  },
  created_at: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW
  },
  updated_at: {
    type: DataTypes.DATE,
    allowNull: true
  }
}, {
  tableName: 'questions',
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at',
  underscored: true,
  indexes: [
    {
      fields: ['status', 'is_active'],
      name: 'idx_questions_status_active'
    },
    {
      fields: ['section_id'],
      name: 'idx_questions_section_id'
    },
    {
      fields: ['created_at', 'id'],
      name: 'idx_questions_created_id'
    }
  ]
});

module.exports = { Question, QuestionType };

