-- Migration: Add missing columns to questions table
-- Run this SQL script to update the database schema to match the Sequelize model
-- Execute these statements one by one in MySQL

-- Step 1: Add status column (ENUM: pending, approved, rejected, inactive)
-- Check if column exists first (run manually if needed)
ALTER TABLE `questions` 
ADD COLUMN `status` ENUM('pending', 'approved', 'rejected', 'inactive') 
NOT NULL DEFAULT 'pending' 
COMMENT 'pending: awaiting approval, approved: can be used in tests, rejected: cannot be used, inactive: deactivated';

-- Step 2: Add source column (ENUM: manual, ai)
ALTER TABLE `questions` 
ADD COLUMN `source` ENUM('manual', 'ai') 
NOT NULL DEFAULT 'manual' 
COMMENT 'manual: created by admin, ai: generated by AI';

-- Step 3: Add is_active column (BOOLEAN/TINYINT)
ALTER TABLE `questions` 
ADD COLUMN `is_active` TINYINT(1) 
NOT NULL DEFAULT 1 
COMMENT 'Whether question is active and can be used in tests';

-- Step 4: Add created_by column (INTEGER, nullable, FK to users)
ALTER TABLE `questions` 
ADD COLUMN `created_by` INT NULL 
COMMENT 'Admin user who created this question';

-- Step 5: Add order_index column
ALTER TABLE `questions` 
ADD COLUMN `order_index` INT 
NOT NULL DEFAULT 0 
COMMENT 'Order within section';

-- Step 6: Add foreign key constraint for created_by (if users table exists)
-- ALTER TABLE `questions` 
-- ADD CONSTRAINT `fk_questions_created_by` 
-- FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) 
-- ON DELETE SET NULL;

-- Step 7: Update existing questions: set status='approved' and is_active=1 for existing records
UPDATE `questions` 
SET `status` = 'approved', `is_active` = 1 
WHERE `status` = 'pending' OR `status` IS NULL;

-- Step 8: Ensure created_at and updated_at exist (these should already exist)
-- If they don't exist, uncomment and run:
-- ALTER TABLE `questions` ADD COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
-- ALTER TABLE `questions` ADD COLUMN `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;

