-- Migration: Unify question creation flow for Admin and AI
-- Adds is_approved column and updates source ENUM values

-- Step 1: Add is_approved column
ALTER TABLE questions
ADD COLUMN IF NOT EXISTS `is_approved` TINYINT(1) NOT NULL DEFAULT 0
COMMENT 'Whether question is approved for use in tests';

-- Step 2: Update source ENUM values
-- Note: This requires dropping and recreating the column if it exists
-- First, check current values and migrate data
UPDATE questions SET source = 'ADMIN' WHERE source = 'manual' OR source IS NULL;
UPDATE questions SET source = 'AI' WHERE source = 'ai';

-- Step 3: Drop and recreate source column with new ENUM values
ALTER TABLE questions
MODIFY COLUMN `source` ENUM('ADMIN', 'AI') NOT NULL DEFAULT 'ADMIN'
COMMENT 'ADMIN: created by admin, AI: generated by AI';

-- Step 4: Set existing admin-created questions as approved
UPDATE questions 
SET is_approved = 1, is_active = 1 
WHERE source = 'ADMIN' AND (is_approved = 0 OR is_approved IS NULL);

-- Step 5: Add index for performance (is_active + is_approved queries)
CREATE INDEX IF NOT EXISTS idx_questions_active_approved 
ON questions(is_active, is_approved);

-- Step 6: Add index for source filtering
CREATE INDEX IF NOT EXISTS idx_questions_source 
ON questions(source);

